# https://docs.helix-editor.com/configuration.html
theme = "ayu_mirage"

[editor]
auto-save = true
bufferline = "multiple"
line-number = "relative"
scrolloff = 5
rulers = [ 81 ]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

