# https://docs.helix-editor.com/configuration.html
theme = "nord"

[editor]
line-number = "relative"
scrolloff = 5
rulers = [ 81 ]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

