# https://docs.helix-editor.com/configuration.html
# vim-maps inspired by https://github.com/LGUG2Z/helix-vim
theme = "ayu_mirage"

[editor]
auto-save = true
bufferline = "multiple"
line-number = "relative"
scrolloff = 5
rulers = [ 81 ]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

# Much needed vim-like mapping
[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

esc = ["collapse_selection", "keep_primary_selection"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
u = ["undo", "collapse_selection"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]